apiVersion: v1
kind: ConfigMap
metadata:
  name: estatekit-api-config
  labels:
    app: estatekit-api
    component: api
    environment: development
data:
  # ASP.NET Core Environment
  ASPNETCORE_ENVIRONMENT: Development

  # AWS KMS Configuration
  AWS__KMS__Region: us-east-1
  AWS__KMS__KeyRotationEnabled: "true"

  # AWS Cognito Configuration  
  AWS__Cognito__Region: us-east-1

  # Cache Settings
  Cache__Provider: Redis
  Cache__DefaultTTLMinutes: "5"

  # Database Configuration
  Database__EnableSensitiveDataLogging: "true"
  Database__MaxRetryCount: "3"
  Database__MaxRetryDelaySeconds: "10"
  Database__EnableSSL: "true"

  # Key Rotation Settings
  KeyRotation__EnableAutomaticRotation: "true"
  KeyRotation__RegularRotationIntervalDays: "1"
  KeyRotation__MaxRetryAttempts: "3"

  # Logging Configuration
  Logging__LogLevel__Default: Debug
  Logging__LogLevel__Microsoft: Debug
  Logging__LogLevel__System: Debug
  Logging__Console__IncludeScopes: "true"

  # API Information
  API__Version: 1.0.0-dev
  API__Title: EstateKit Personal Information API - Development

  # Observability Settings
  Metrics__Enabled: "true"
  Tracing__Enabled: "true"
  HealthCheck__Enabled: "true"