apiVersion: v1
kind: ConfigMap
metadata:
  name: estatekit-api-config
  labels:
    app: estatekit-api
    component: api
    environment: staging
data:
  # Environment Configuration
  ASPNETCORE_ENVIRONMENT: "Staging"
  AWS__Region: "us-east-1"

  # AWS KMS Configuration
  AWS__KMS__KeyRotationEnabled: "true"

  # Cache Configuration
  Cache__Provider: "Redis"
  Cache__DefaultTTLMinutes: "15"

  # Database Security Configuration
  Database__EnableSensitiveDataLogging: "false"
  Database__MaxRetryCount: "3"
  Database__EnableSSL: "true"

  # Key Rotation Security Settings
  KeyRotation__EnableAutomaticRotation: "true"
  KeyRotation__RegularRotationIntervalDays: "90"
  KeyRotation__MaxRetryAttempts: "3"

  # Logging Configuration
  Logging__LogLevel__Default: "Information"
  Logging__Console__IncludeScopes: "true"

  # API Version
  API__Version: "1.0.0"

  # Observability Settings
  Metrics__Enabled: "true"
  Tracing__Enabled: "true"
  HealthCheck__Enabled: "true"