apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Define staging namespace
namespace: estatekit-api-staging

# Add staging prefix to all resources
namePrefix: staging-

# Common labels for all resources
commonLabels:
  environment: staging
  app.kubernetes.io/environment: staging
  app.kubernetes.io/part-of: estatekit-api
  app.kubernetes.io/managed-by: kustomize
  security.estatekit.com/compliance-level: pre-production

# Common annotations for all resources
commonAnnotations:
  environment.estatekit.com/name: staging
  environment.estatekit.com/type: pre-production
  deployment.estatekit.com/strategy: blue-green
  monitoring.estatekit.com/enabled: "true"
  security.estatekit.com/encryption-enabled: "true"

# Base resources to customize
resources:
  - ../../base

# Strategic merge patches
patchesStrategicMerge:
  - configmap.yaml
  - hpa.yaml
  - network-policy.yaml

# Set replica count for staging environment
replicas:
  - name: estatekit-api
    count: 3

# Configure container images
images:
  - name: estatekit-api
    newName: estatekit-api
    newTag: staging

# Generate ConfigMap with staging-specific configurations
configMapGenerator:
  - name: estatekit-api-config
    behavior: merge
    envs:
      - staging.env
    files:
      - config/logging.yaml
      - config/monitoring.yaml