version: '3.8'

services:
  # EstateKit Personal Information API service
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5000:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__PostgreSQL=Host=postgres;Database=estatekit;Username=dev_user;Password=dev_password
      - ConnectionStrings__Redis=redis:6379
      - AWS__ServiceURL=http://localstack:4566
      - AWS__Region=us-east-1
    volumes:
      - ./src:/src
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      localstack:
        condition: service_healthy
    networks:
      - estatekit_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # PostgreSQL database for key storage
  postgres:
    image: postgres:16.0
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=estatekit
      - POSTGRES_USER=dev_user
      - POSTGRES_PASSWORD=dev_password
      - POSTGRES_INITDB_ARGS=--auth-local=scram-sha-256
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - estatekit_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev_user -d estatekit"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis cache for key caching
  redis:
    image: redis:7.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - estatekit_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    command: redis-server --appendonly yes

  # LocalStack for AWS service emulation
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=kms,cognito
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack_data:/tmp/localstack
    networks:
      - estatekit_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  estatekit_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  localstack_data:
    driver: local