apiVersion: v1
kind: Secret
metadata:
  name: estatekit-api-secrets
  labels:
    app: estatekit-api
    component: api
type: Opaque
data:
  # Database configuration
  Database__ConnectionString: ${BASE64_DB_CONNECTION}
  Database__Password: ${BASE64_DB_PASSWORD}

  # AWS credentials and configuration
  AWS__Credentials__AccessKey: ${BASE64_AWS_ACCESS_KEY}
  AWS__Credentials__SecretKey: ${BASE64_AWS_SECRET_KEY}
  AWS__KMS__KeyId: ${BASE64_KMS_KEY_ID}
  
  # AWS Cognito configuration
  AWS__Cognito__UserPoolId: ${BASE64_COGNITO_USER_POOL_ID}
  AWS__Cognito__ClientId: ${BASE64_COGNITO_CLIENT_ID}
  AWS__Cognito__ClientSecret: ${BASE64_COGNITO_CLIENT_SECRET}

  # Cache configuration
  Cache__ConnectionString: ${BASE64_REDIS_CONNECTION}
  Cache__Password: ${BASE64_REDIS_PASSWORD}

  # Security keys
  JWT__SecurityKey: ${BASE64_JWT_KEY}
  API__SecurityKey: ${BASE64_API_KEY}