apiVersion: v1
kind: ServiceAccount
metadata:
  name: estatekit-api-sa
  namespace: estatekit-api
  labels:
    app.kubernetes.io/name: estatekit-api
    app.kubernetes.io/part-of: estatekit
    app.kubernetes.io/managed-by: kustomize
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::${AWS_ACCOUNT_ID}:role/estatekit-api-role
    kubernetes.io/description: Service account for EstateKit API pods to access AWS services
    eks.amazonaws.com/sts-regional-endpoints: "true"